### ISSUE TITLE
Issues with dbsns and dbvis.

### ISSUE THREAD

**Issue by AshleyWoods** [mcglinnlab/soar#10]
They don't tell you anywhere on this page: https://www.r-bloggers.com/visualizing-bdsns-data-using-bdvis/ that the package 'igraph' is required, but it is. I'm also getting errors such as 
"Error in rsqlite_send_query(conn@ptr, statement) : 
  no such table: Flickrrec"
I can't figure out what this means? I've checked the instructions and they don't mention making that table anywhere either.

**Comment by dmcglinn** [comment]
Thanks for looking into this. It would be a good idea to submit a bug report to the package maintainer. Also I suggest given this road block you switch to trying out rebird

**Comment by AshleyWoods** [comment]
I uploaded my test of the rebird code to the github page. I'll look into reporting the bug after fiddling some more to make sure I haven't missed something.
