### ISSUE TITLE
Processing the Data

### ISSUE THREAD

**Issue by AshleyWoods** [mcglinnlab/soar#12]
The data can now be imported into the app based on lat/long, political boundaries, date, name, and any combination of those. However, did we discuss how we were going to process the data? It's too large for me to open and I don't quite understand the errors it's throwing right now. I believe the issue is in addCircleMarkers() in output$world_map. The error is: "Error in UseMethod: no applicable method for 'metaData' applied to an object of class "NULL" "

**Comment by dmcglinn** [comment]
Which version of the data are you testing this code on right now. Just the caretta caretta pull we were playing around with yesterday or the all birds dataset?

**Comment by AshleyWoods** [comment]
I'm actually running the app to download a gbif 'Caretta caretta' data set. (and deleting it when I'm done with the test)

**Comment by AshleyWoods** [comment]
I think I found the problem, the data downloads as a zip file, not as a csv. I'm having trouble finding a command to extract it without having to know the exact path to the file I want to unzip. However, if someone is running the app on their computer the path would change. Do you know a command that would work?

**Comment by AshleyWoods** [comment]
After more tinkering, I was very wrong about what the problem was. I can plot the data using the same commands outside of the shiny app on the same data without unzipping it. I think, based on the error, that the method is trying to map the 'meta' variable rather than the 'dat' variable. I have fixed the issue.

**Comment by dmcglinn** [comment]
Great thanks for the update!
