### ISSUE TITLE
Adding ability to authenticate to inat

### ISSUE THREAD

**Issue by dmcglinn** [mcglinnlab/soar#5]
This will be important if we want users to be able to access their project data from our package. Also this would be important if they are approved to get un-obscured coordinates. Here is some info on this: 
https://www.inaturalist.org/pages/api+reference

**Comment by AshleyWoods** [comment]
So would it be an optional field in the app? Kind of like the longitude and latitude where they could check a box to log in and it would open the username and password fields?

**Comment by dmcglinn** [comment]
Yes I think so. This would be primarily if they wanted to download their project records. They would need to authenticate to inat before they would let them get all the project observations.
