### ISSUE TITLE
I can't find the API for Flickr in R

### ISSUE THREAD

**Issue by AshleyWoods** [mcglinnlab/soar#8]
The paper pointed me to this website -> https://www.flickr.com/services/api/
But I cannot find the API for R.

**Comment by dmcglinn** [comment]
You need to use the package: `bdsns` also the package `bdvis` will be useful for visualizing results. See this link:  https://www.r-bloggers.com/visualizing-bdsns-data-using-bdvis/

It is strange in the [paper](https://www.sciencedirect.com/science/article/pii/S1574954114001186) they don't explicitly mention the R packages (I suppose the were shared after the paper was accepte?)
