### ISSUE TITLE
Permission required for API Flickr access.

### ISSUE THREAD

**Issue by AshleyWoods** [mcglinnlab/soar#9]
I can't test it without a key. Should I apply? https://www.flickr.com/services/api/misc.api_keys.html

**Comment by dmcglinn** [comment]
the webpage says that if you're using it for non-commercial purposes you don't need a key. Am I missing something?

**Comment by AshleyWoods** [comment]
Just that I have to apply for it. They want a description of what we're building, the name, and there's a warning says the app will be associated with the woodsy913 flickr account I've got that I'm applying through.

**Comment by dmcglinn** [comment]
ahh, yes please do go ahead and get the key. thanks!
